[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://mqrpjnwotddnfihkwyyl.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcnBqbndvdGRkbmZpaGt3eXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Njc1NzgsImV4cCI6MjA2NjM0MzU3OH0.Z43otQwtAzDrjJyA6HscdDSRmAXBXMvr5sUyWbfUwNo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200